// Mapping centralisé LNI → Phosphor Icons
// Toutes les icônes du projet passent par ce fichier.
// Importer depuis @/lib/icons — ne jamais importer directement @phosphor-icons/react dans les composants.
export {
  // Noms Phosphor natifs utilisés directement dans les composants
  Alarm,
  ArrowLeft,
  ArrowRight,
  Brain,
  Briefcase,
  Calculator,
  Calendar,
  Car,
  CaretDown,
  CaretLeft,
  CaretRight,
  Chat,
  Chats,
  Check,
  CheckCircle,
  Clock,
  Cloud,
  Compass,
  CurrencyDollar,
  Database,
  Desktop,
  DeviceMobile,
  DownloadSimple,
  Envelope,
  Eye,
  FileText,
  Funnel,
  Globe,
  HardDrive,
  Headphones,
  Heart,
  HeartbeatIcon,
  House,
  Infinity,
  Info,
  Lightning,
  Lightbulb,
  LinkedinLogo,
  Link,
  List,
  Lock,
  MapPin,
  MapTrifold,
  MagnifyingGlass,
  Microphone,
  MicrosoftTeamsLogo,
  MusicNote,
  Phone,
  PhoneCall,
  Play,
  PlugCharging,
  Pulse,
  Question,
  Quotes,
  ArrowsClockwise,
  Rocket,
  Scales,
  Seal,
  ShareNetwork,
  Shield,
  ShoppingCart,
  SpeakerHigh,
  Star,
  Tag,
  Target,
  TextT,
  Timer,
  TreeStructure,
  TrendUp,
  UserCircle,
  Users,
  VideoCamera,
  Warning,
  WhatsappLogo,
  WifiHigh,
  X,
  XCircle,
  Buildings,
  ChartBar,
  Gear,
  Wallet,
  PhoneDisconnect,
  ShieldCheck,
  Medal,
  Storefront,
} from "@phosphor-icons/react/dist/ssr";

// Alias sémantiques LNI (pour compatibilité avec le code existant)
export {
  Buildings as Apartment,
  ChartBar as BarChart,
  Lightning as Bolt,
  Lightning as BoltAlt,
  Chat as Bubble,
  Lightbulb as Bulb,
  ShoppingCart as Cart,
  Seal as Certificate,
  Check as Checkmark,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  X as Close,
  Gear as Cog,
  Chat as Comments,
  Chats as CommentsAlt,
  XCircle as CrossCircle,
  Compass as DirectionAlt,
  Desktop as Display,
  CurrencyDollar as Dollar,
  DownloadSimple as Download,
  TrendUp as Grow,
  Headphones as Headphone,
  Headphones as HeadphoneAlt,
  HeartbeatIcon as HeartMonitor,
  House as Home,
  Info as Information,
  MapTrifold as Map,
  MapPin as MapMarker,
  List as Menu,
  MicrosoftTeamsLogo as Microsoft,
  DeviceMobile as Mobile,
  Wallet as MoneyLocation,
  MusicNote as Music,
  TreeStructure as Network,
  PhoneCall as PhoneSet,
  PlugCharging as Plug,
  Shield as Protection,
  Question as QuestionCircle,
  Quotes as Quotation,
  ArrowsClockwise as Reload,
  MagnifyingGlass as SearchAlt,
  HardDrive as Server,
  ShareNetwork as ShareAlt,
  WifiHigh as Signal,
  Star as StarFilled,
  TrendUp as StatsUp,
  Headphones as Support,
  ArrowsClockwise as Sync,
  TextT as TextFormat,
  Lock as Unlock,
  UserCircle as User,
  VideoCamera as Video,
  SpeakerHigh as Volume,
  WhatsappLogo as Whatsapp,
  Globe as World,
} from "@phosphor-icons/react/dist/ssr";

// Re-export du type Icon pour les props
export type { Icon } from "@phosphor-icons/react";
